steps:
  # Pull previous image for layer caching
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - '-c'
      - 'docker pull gcr.io/$PROJECT_ID/earnings-scraper-api:latest || exit 0'

  # Build the container image with cache
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build', 
      '--cache-from', 'gcr.io/$PROJECT_ID/earnings-scraper-api:latest',
      '-t', 'gcr.io/$PROJECT_ID/earnings-scraper-api:$COMMIT_SHA',
      '-t', 'gcr.io/$PROJECT_ID/earnings-scraper-api:latest',
      '.'
    ]

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/earnings-scraper-api:$COMMIT_SHA']
  
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/earnings-scraper-api:latest']

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: [
      'run', 'deploy', 'earnings-scraper',
      '--image', 'gcr.io/$PROJECT_ID/earnings-scraper-api:$COMMIT_SHA',
      '--region', 'us-central1',
      '--platform', 'managed',
      '--allow-unauthenticated',
      '--port', '8080'
    ]

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'  # Faster build machine

images:
  - 'gcr.io/$PROJECT_ID/earnings-scraper-api:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/earnings-scraper-api:latest' 